# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rest_to_main_pb2 as rest__to__main__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in rest_to_main_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TransferFileServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.transferFile = channel.stream_unary(
                '/TransferFileService/transferFile',
                request_serializer=rest__to__main__pb2.transferRequest.SerializeToString,
                response_deserializer=rest__to__main__pb2.transferResponse.FromString,
                _registered_method=True)


class TransferFileServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def transferFile(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransferFileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'transferFile': grpc.stream_unary_rpc_method_handler(
                    servicer.transferFile,
                    request_deserializer=rest__to__main__pb2.transferRequest.FromString,
                    response_serializer=rest__to__main__pb2.transferResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TransferFileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('TransferFileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TransferFileService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def transferFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/TransferFileService/transferFile',
            rest__to__main__pb2.transferRequest.SerializeToString,
            rest__to__main__pb2.transferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
